name: ws

networks:
  net:
    name: ws-net

services:
  aggregator:
    build:
      context: ./controller
    container_name: ws-aggregator
    ports:
      - ${AGGREGATOR_PORT:-3001}:${AGGREGATOR_PORT:-3001}
    networks: [ net ]
    env_file:
      - .env

  client:
    build:
      context: ./client
    networks: [ net ]
    env_file:
      - .env
    deploy:
      replicas: 3

  node:
    build:
      context: ./node
    container_name: ws-node
    networks: [ net ]
    env_file:
      - .env
